services:
    icap.listener.blog_listener:
        class: ICAP\BlogBundle\Listener\BlogListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_form_icap_blog, method: onCreateForm }
            - { name: kernel.event_listener, event: create_icap_blog, method: onCreate }
            - { name: kernel.event_listener, event: open_icap_blog, method: onOpen }
            - { name: kernel.event_listener, event: delete_icap_blog, method: onDelete }
            - { name: kernel.event_listener, event: copy_icap_blog, method: onCopy }

    icap.listener.log_listener:
        class: ICAP\BlogBundle\Listener\LogListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_log_details_resource-icap_blog-post_create, method: onPostCreateLogDetails }
            - { name: kernel.event_listener, event: create_log_list_item_resource-icap_blog-post_create, method: onCreateLogListItem }
            - { name: kernel.event_listener, event: create_log_list_item_resource-icap_blog-post_read, method: onCreateLogListItem }
