services:
    claroline.listener.blog_listener:
        class: ICAP\BlogBundle\Listener\BlogListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_form_icap_blog, method: onCreateForm }
            - { name: kernel.event_listener, event: create_icap_blog, method: onCreate }
            - { name: kernel.event_listener, event: open_icap_blog, method: onOpen }
            - { name: kernel.event_listener, event: delete_icap_blog, method: onDelete }
            - { name: kernel.event_listener, event: copy_icap_blog, method: onCopy }
            - { name: kernel.event_listener, event: create_log_list_item_icap_blog, method: onCreateLogListItem }
            - { name: kernel.event_listener, event: create_log_details_icap_blog, method: onCreateLogDetails }
